main: io.github.lukeeff.schematiclightapi.SchematicLightAPI
version: 1.0.0
name: SchematicLightAPI
commands:
  schematic:
    description: Set the schematic. Do not include file type in name. Name only.
    usage: /schematic <schematic name>
    permission: im.a.noob
    permission-message: You do not have permission to be an noob!